In [1]:
from sklearn.metrics.pairwise import sigmoid_kernel
from sklearn.gaussian_process.kernels import RBF
import numpy as np
import matplotlib.pyplot as plt
from sklearn import svm, datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, confusion_matrix

In [2]:
K2 = sigmoid_kernel
K1 = RBF(1.0)

In [3]:
# import some data to play with
iris = datasets.load_iris()
X = iris.data  # we only take the first two features. We could
# avoid this ugly slicing by using a two-dim dataset
Y = iris.target

In [4]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((120, 4), (30, 4), (120,), (30,))

In [5]:
def senario(input_kernel):
    # we create an instance of SVM and fit out data.
    clf = svm.SVC(kernel=input_kernel)
    clf.fit(X_train, y_train)

    pred = clf.predict(X_test)
    print()

    print(f'accuracy : {accuracy_score(y_test, pred)}')
    print(f'confusion matrix \n {confusion_matrix(y_test, pred)}')

# 1

In [6]:
def kernel_1(X, Y):
    return K1(X, Y) + K2(X, Y)

In [7]:
print("kernel 1")
senario(kernel_1)

kernel 1

accuracy : 0.9666666666666667
confusion matrix 
 [[ 9  0  0]
 [ 0  9  0]
 [ 0  1 11]]


# 2

In [8]:
print("kernel 2")
def kernel_2(X, Y):
    return K1(X, Y) - K2(X, Y)
senario(kernel_2)

kernel 2

accuracy : 0.9666666666666667
confusion matrix 
 [[ 9  0  0]
 [ 0  9  0]
 [ 0  1 11]]


# 3

In [9]:
print("kernel 3")
def kernel_3(X, Y , alpha = 0.5):
    return K1(X, Y) * alpha


senario(kernel_3)

kernel 3

accuracy : 0.9666666666666667
confusion matrix 
 [[ 9  0  0]
 [ 0  9  0]
 [ 0  1 11]]


# 4

In [10]:
print("kernel 4")
def kernel_4(X, Y):
    return K1(X, Y) * K2(X, Y)
senario(kernel_4)

kernel 4

accuracy : 0.9666666666666667
confusion matrix 
 [[ 9  0  0]
 [ 0  9  0]
 [ 0  1 11]]


# others

In [11]:
print(f'RBF only')
senario('rbf')

RBF only

accuracy : 0.9666666666666667
confusion matrix 
 [[ 9  0  0]
 [ 0  9  0]
 [ 0  1 11]]


In [12]:
print(f'sigmoid only')
senario('sigmoid')

sigmoid only

accuracy : 0.16666666666666666
confusion matrix 
 [[ 4  5  0]
 [ 8  1  0]
 [12  0  0]]
